name: Push to Another Repository

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  permissions:
    contents: read
    pages: write
    id-token: write
  concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run NodeJs
        run: |
          npm install pnpm -g
          pnpm install
          pnpm run docs:build
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-page
          FOLDER: docs/.vitepress/dist
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
